DROP TABLE IF EXISTS "user_selection";
DROP TABLE IF EXISTS "training_item";
DROP TABLE IF EXISTS "learning_object";
DROP TABLE IF EXISTS "training_session";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "radical_group";
DROP TABLE IF EXISTS "training_mode";
DROP TABLE IF EXISTS "role";


-- Таблицы без внешних ключей

CREATE TABLE "role" (
	"id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE "training_mode" (
	"id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50),
	"access_level" INTEGER NOT NULL,
	"description" VARCHAR(255) 
);

CREATE TABLE "radical_group" (
	"id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) UNIQUE NOT NULL,
	"slug" VARCHAR(50) UNIQUE NOT NULL,
	"description" VARCHAR(255) NOT NULL 
);

-- Таблицы, зависящие от других таблиц

CREATE TABLE "user" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(50) UNIQUE NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"first_name" VARCHAR(100) NOT NULL,
	"last_name" VARCHAR(100) NOT NULL,
	"email" VARCHAR(100) NOT NULL,
	"date_of_birth" DATE,
	"want_spam" BOOLEAN DEFAULT FALSE,
	"role_id" INT NOT NULL REFERENCES "role" ("id")
	
);

CREATE TABLE "training_session" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"mode_id" INTEGER NOT NULL,
	"date_started" DATE NOT NULL,
	"date_ended" DATE,
	"result" VARCHAR(20),
	PRIMARY KEY ("id"),
	FOREIGN KEY ("user_id") REFERENCES "user" ("id"),
	FOREIGN KEY ("mode_id") REFERENCES "training_mode" ("id")
);

CREATE TABLE "learning_object" (
	"id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"symbol" VARCHAR(10) NOT NULL,
	"pinyin" VARCHAR(50) NOT NULL,
	"tone" SMALLINT,
	"meaning" VARCHAR(255) NOT NULL,
	"strokes" INTEGER NOT NULL,
	"description" VARCHAR(255),
	"slug" VARCHAR(50) UNIQUE NOT NULL,
	"group_id" INTEGER REFERENCES "radical_group" ("id")
);

CREATE TABLE "training_item" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"session_id" INTEGER NOT NULL,
	"object_id" INTEGER NOT NULL REFERENCES "learning_object" ("id"),
	"is_correct" BOOLEAN,
	"user_answer" VARCHAR(255),
	PRIMARY KEY ("id"),
	FOREIGN KEY ("session_id") REFERENCES "training_session" ("id")
);

CREATE TABLE "user_selection" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"object_id" INTEGER NOT NULL REFERENCES "learning_object" ("id"),
	"saved_name" VARCHAR(100) NOT NULL,
	PRIMARY KEY ("id"),
	FOREIGN KEY ("user_id") REFERENCES "user" ("id")
);
